steps:
  - name: gcr.io/cloud-builders/gcloud
    id: "decrypt secrets"
    args:
      - kms
      - decrypt
      - "--ciphertext-file=.env.enc"
      - "--plaintext-file=.env"
      - "--location=global"
      - "--keyring=git-secrets"
      - "--key=${_SERVICE_NAME}"
  - name: gcr.io/cloud-builders/docker
    id: "build container"
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    id: "tag container"
    args:
      - tag
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"
  - name: gcr.io/cloud-builders/docker
    id: "push container"
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"
      # - "--all-tags"
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args: [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        # "-e",
        # "CI=True",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]
  - name: gcr.io/cloud-builders/gcloud
    id: "deploy to cloud run"
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region"
      - ${_REGION}
      - "--platform"
      - managed
      - "--timeout"
      - 10m
    # This will be ran in async after build container
  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]
    waitFor:
      - "build container"
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: chari-lake
  _INSTANCE_NAME: iconicto
images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
