name: CI/CD Pipeline

on:
  push:
    branches:
    - master

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure docker
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login ghcr.io -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Set image name
        run: echo ::set-env name=IMAGE_NAME::ghcr.io/mrsupiri/$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      - name: Build container
        run: docker build -t $IMAGE_NAME .
      - name: Add container tags
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:commit-${GITHUB_SHA:0:8}
          docker tag $IMAGE_NAME $IMAGE_NAME:build-${GITHUB_RUN_NUMBER}
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
      - name: Push to docker registry
        run: docker push $IMAGE_NAME